export const en = {
  nav: {
    home: "Home",
    aiRoute: "AI Route Planner",
    localGuide: "Local Guides",
    unseenPlaces: "Unseen Places",
    travelBuddy: "Travel Buddy",
    transport: "Transport",
  },
  hero: {
    badge: "POWERED BY TidCORS Team",
    title1: "Uncover the",
    title2: "Hidden Thailand",
    subtitle: "Skip the tourist traps. Let our AI craft your perfect itinerary with verified locals and hidden gems.",
    whereTo: "Where to?",
    whereToPlaceholder: "e.g. Chiang Mai, Islands...",
    travelStyle: "Travel Style",
    duration: "Duration",
    generateBtn: "Generate Itinerary",
  },
  destinations: {
    title: "Trending Unseen",
    subtitle: "Hand-picked destinations that remain untouched by mass tourism.",
    exploreBtn: "Explore All Places",
    places: [
      { title: "Khao Sok National Park", location: "Surat Thani" },
      { title: "Wat Phra That Hariphunchai", location: "Lampang" },
      { title: "Koh Kood", location: "Trat" }
    ]
  },
  ecosystem: {
    title: "An Ecosystem Built for You",
    subtitle: "Everything you need for a seamless, safe, and unforgettable journey in Thailand.",
    guidesTitle: "Verified Local Guides",
    guidesDesc: "Connect with knowledgeable locals who know the hidden gems. Every guide passes strict identity verification.",
    guidesBtn: "Meet Guides",
    buddyTitle: "Travel Buddy Matcher",
    buddyDesc: "Find like-minded travelers to share experiences and split costs for transportation and accommodations.",
    buddyBtn: "Find Buddies",
    transportTitle: "Transparent Transport",
    transportDesc: "No haggling, no scams. Book verified drivers with upfront, transparent pricing directly through the app.",
    transportBtn: "Book a Ride",
  },
  footer: {
    copyright: "© 2026 Thai Unseen Agent By TidCORS Team. Developed for Super AI Hackathon."
  },
  pages: {
    aiRoute: {
      title: "AI Route Planner",
      subtitle: "Your perfect, personalized itinerary generated by AI.",
      editBtn: "Edit Preferences",
      saveBtn: "Save to My Trips"
    },
    buddies: {
      title: "Travel Buddy Matcher",
      subtitle: "Find companions, share costs, and make memories.",
      profileBtn: "My Profile & Preferences"
    },
    guides: {
      title: "Verified Local Guides",
      subtitle: "Connect with locals who know the real Thailand.",
      beGuideBtn: "Become a Guide"
    },
    transport: {
      title: "Transparent Transport",
      subtitle: "Book verified drivers with transparent, upfront pricing.",
      historyBtn: "My Bookings"
    },
    unseen: {
      title: "Unseen Destinations",
      subtitle: "Discover hidden gems away from the tourist crowds.",
      filterBtn: "Filters"
    }
  }
};

export type Dictionary = typeof en;
